---
# tasks file for mongoDB setup

- name: install mongoDB
  apt: 
    name: mongodb
    state: present
    update_cache: yes

- name: copy config file
  copy:
    src: mongodb.conf
    dest: /etc/mongodb.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mongodb

- name: Ensure mongodb is running and and enabled to start automatically on reboots
  systemd:
    name: mongodb
    enabled: yes
    state: started

- name: install pip
  apt: 
    name: python3-pip
    state: present

- name: Install pymongo python package
  pip:
    name: pymongo

- mongodb_user:
    database: admin
    name: test-user
    password: 12345
    state: present
